plugins { id 'com.android.application' }
android {
    namespace 'com.kot46.cs16serversync'
    compileSdk 35
    defaultConfig {
        applicationId 'com.kot46.cs16serversync'
        minSdk 23
        targetSdk 35
        versionCode 12
        versionName '1.2'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
dependencies {
    implementation 'androidx.documentfile:documentfile:1.0.1'
    implementation 'androidx.work:work-runtime:2.9.1'
}
